version: '3.8'

services:
  oracle-db:
    image: gvenzl/oracle-xe:21.3.0-slim
    container_name: oracle-xe
    ports:
      - "1521:1521"  # Porta padrão para o Oracle DB
      - "5500:5500"  # Porta para o Oracle Enterprise Manager (opcional)
    environment:
      - ORACLE_PASSWORD=87654321  # Senha para o usuário SYS e SYSTEM
    volumes:
      - oracle-data:/opt/oracle/oradata  # Persistência de dados no volume

volumes:
  oracle-data:
    driver: local
